language: node_js
dist: trusty
node_js:
  - 6.10
sudo: required
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  - npm run test:coverage
  - npm run lint
  - npm run build:publish:gh
